# Generated by Django 5.0.7 on 2025-03-26 03:38

import django.core.validators
import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='face_recognition',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='base_clock',
            field=models.FloatField(help_text='Base clock speed in GHz'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='boost_clock',
            field=models.FloatField(help_text='Boost clock speed in GHz'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Product image (required, must be square 1:1 ratio)', upload_to='product_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), store.models.validate_square_image]),
        ),
        migrations.CreateModel(
            name='ComparisonList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('product_type', models.CharField(help_text="Type of products in this comparison (e.g., 'GPU', 'Laptop')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comparison List',
                'verbose_name_plural': 'Comparison Lists',
            },
        ),
        migrations.CreateModel(
            name='ComparisonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('comparison_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.comparisonlist')),
            ],
            options={
                'verbose_name': 'Comparison Item',
                'verbose_name_plural': 'Comparison Items',
                'ordering': ['added_at'],
            },
        ),
    ]
