# Generated by Django 5.0.7 on 2025-03-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal title for this slide (not displayed)', max_length=100)),
                ('heading', models.CharField(help_text='Main heading displayed on the slide', max_length=100)),
                ('subheading', models.CharField(blank=True, help_text='Optional subheading displayed below the main heading', max_length=200)),
                ('image', models.ImageField(help_text='Image for this slide (recommended size: 1920x800px)', upload_to='sliders/')),
                ('button_text', models.CharField(blank=True, help_text='Optional button text (leave empty for no button)', max_length=30)),
                ('button_link', models.CharField(blank=True, help_text='URL for the button (required if button text is provided)', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which slides are displayed (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slide is currently displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'ordering': ['order', 'id'],
            },
        ),
    ]
