# Generated by Django 5.0.7 on 2025-03-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='description',
            field=models.TextField(default='Stylish and functional computer case with excellent airflow design. Features tool-less installation and multiple drive bays for easy customization.', help_text='Detailed description of the case'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='description',
            field=models.TextField(default='Powerful processor offering excellent multi-core performance for demanding applications. Energy-efficient design with advanced architecture.', help_text='Detailed description of the CPU'),
        ),
        migrations.AddField(
            model_name='headset',
            name='description',
            field=models.TextField(default='Immersive audio headset with comfortable ear cups and clear microphone. Designed for extended gaming sessions with excellent sound positioning.', help_text='Detailed description of the headset'),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='description',
            field=models.TextField(default='Responsive keyboard with comfortable key travel and durable switches. Features anti-ghosting technology for accurate input during intensive use.', help_text='Detailed description of the keyboard'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='description',
            field=models.TextField(default='Powerful laptop combining performance and portability. Features high-quality display, responsive keyboard, and excellent battery life for productivity on the go.', help_text='Detailed description of the laptop'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='description',
            field=models.TextField(default='High-quality display with excellent color accuracy and response time. Features ergonomic design and multiple connectivity options for versatile use.', help_text='Detailed description of the monitor'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='description',
            field=models.TextField(default='Feature-rich motherboard with excellent build quality and component compatibility. Designed for stability and performance with multiple expansion options.', help_text='Detailed description of the motherboard'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='description',
            field=models.TextField(default='Ergonomic mouse with precise tracking and customizable buttons. Designed for comfort during extended use with durable construction.', help_text='Detailed description of the mouse'),
        ),
        migrations.AddField(
            model_name='otheraccessory',
            name='description',
            field=models.TextField(default='High-quality accessory designed to enhance your computing experience. Features durable construction and excellent compatibility.', help_text='Detailed description of the accessory'),
        ),
        migrations.AddField(
            model_name='psu',
            name='description',
            field=models.TextField(default='Reliable power supply unit with excellent efficiency ratings. Features stable power delivery and protective circuitry for system safety.', help_text='Detailed description of the PSU'),
        ),
        migrations.AddField(
            model_name='ram',
            name='description',
            field=models.TextField(default='High-speed memory module designed for optimal system performance. Provides reliable operation with excellent compatibility across various systems.', help_text='Detailed description of the RAM'),
        ),
        migrations.AddField(
            model_name='slider',
            name='description',
            field=models.TextField(default='Featured promotional content for the homepage slider.', help_text='Additional information about this slider (not displayed on frontend)'),
        ),
        migrations.AddField(
            model_name='speakers',
            name='description',
            field=models.TextField(default='Premium speakers delivering rich, balanced sound with deep bass response. Compact design with multiple connectivity options for versatile setup.', help_text='Detailed description of the speakers'),
        ),
        migrations.AddField(
            model_name='storagedevice',
            name='description',
            field=models.TextField(default='High-capacity storage solution with excellent read/write speeds. Reliable performance for both everyday use and demanding applications.', help_text='Detailed description of the storage device'),
        ),
        migrations.AddField(
            model_name='tablet',
            name='description',
            field=models.TextField(default='Versatile tablet with responsive touchscreen and powerful performance. Features long battery life and excellent display quality for both work and entertainment.', help_text='Detailed description of the tablet'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='description',
            field=models.TextField(default='High-performance graphics card designed for gaming and professional applications. Features advanced cooling technology and excellent visual processing capabilities.', help_text='Detailed description of the GPU'),
        ),
    ]
