# Generated by Django 5.0.7 on 2025-03-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_case_description_cpu_description_headset_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='usb_ports',
            field=models.JSONField(blank=True, help_text='List of USB ports and their types', null=True),
        ),
    ]
