# Generated by Django 4.2.16 on 2025-04-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Primary contact number to display site-wide.', max_length=32)),
            ],
            options={
                'verbose_name': 'Site Number',
                'verbose_name_plural': 'Site Number',
            },
        ),
    ]
