# Generated by Django 4.2.16 on 2025-04-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_sitenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='fan_connectors',
            field=models.JSONField(blank=True, default=list, help_text="List of fan connectors (e.g., ['5V 3 Pin (ARGB)', '4 Pin PWM'])", null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='fan_speeds',
            field=models.JSONField(blank=True, default=dict, help_text="Dictionary of fan speeds (e.g., {'140mm': '500-1200 RPM', '120mm': '500-1400 RPM'})", null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='io_ports',
            field=models.JSONField(blank=True, default=list, help_text="List of front-panel I/O ports (e.g., ['USB 3.0', 'USB Type-C', 'Audio Jack', 'RGB Button'])", null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='preinstalled_fans',
            field=models.JSONField(blank=True, default=list, help_text="List of pre-installed fans with details (e.g., [{'location': 'Front', 'size': 140, 'type': 'ARGB'}])", null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='supported_motherboards',
            field=models.JSONField(blank=True, default=list, help_text="List of motherboard sizes supported (e.g., ['ATX', 'Micro-ATX', 'Mini-ITX'])", null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='water_cooling_support',
            field=models.JSONField(blank=True, default=dict, help_text="Dictionary of supported radiator sizes by location (e.g., {'Front': ['360mm', '280mm'], 'Top': ['360mm']})", null=True),
        ),
    ]
